# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
gem 'tty-prompt', '~> 0.19.0'
gem 'colorize', '~> 0.8.1'
gem 'rest-client', '~> 1.8'
gem 'nokogiri'
gem 'whirly'
gem 'paint'